(() => {
  const escape = value => String(value || '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char]));
  let currentUser = null;
  const api = async (url, options = {}) => { const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, credentials: 'same-origin' }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || 'Request failed.'); return data; };
  const toast = message => { let node = document.getElementById('homebite-toast'); if (!node) { node = document.createElement('div'); node.id = 'homebite-toast'; node.className = 'fixed bottom-5 right-5 z-[100] rounded-2xl bg-stone-900 px-5 py-3 text-sm font-semibold text-white shadow-2xl'; document.body.append(node); } node.textContent = message; node.classList.remove('hidden'); setTimeout(() => node.classList.add('hidden'), 2800); };
  const getUser = async () => { try { currentUser = (await api('/api/auth/me')).user; } catch { currentUser = null; } return currentUser; };
  const favourites = () => JSON.parse(localStorage.getItem('homebite_favourites') || '[]');
  const setFavourites = list => localStorage.setItem('homebite_favourites', JSON.stringify(list));
  const card = (meal, orderable = false) => { const isFavourite = favourites().includes(meal.id); return `<article class="rounded-2xl overflow-hidden border border-orange-100 bg-white shadow-sm"><img class="h-36 w-full object-cover" src="${escape(meal.image || 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=80')}" alt="${escape(meal.name)}"><div class="p-4"><div class="flex items-start justify-between gap-2"><h3 class="font-serif text-xl font-bold">${escape(meal.name)}</h3><button data-favourite="${meal.id}" class="text-xl" aria-label="Favourite">${isFavourite ? '♥' : '♡'}</button></div><p class="mt-1 text-sm text-stone-500">${escape(meal.cuisine)} · ${escape(meal.diet)} · by ${escape(meal.cookName)}</p><div class="mt-4 flex items-center justify-between"><strong class="text-orange-600">₹${Number(meal.price).toFixed(0)}</strong>${orderable ? `<button data-order="${meal.id}" class="rounded-xl bg-orange-500 px-3 py-2 text-sm font-semibold text-white">Order</button>` : ''}</div></div></article>`; };
  const bindCards = (scope, meals) => { scope.querySelectorAll('[data-favourite]').forEach(button => button.onclick = () => { const id = button.dataset.favourite; const list = favourites(); setFavourites(list.includes(id) ? list.filter(value => value !== id) : [...list, id]); button.textContent = list.includes(id) ? '♡' : '♥'; toast('Favourites updated'); }); scope.querySelectorAll('[data-order]').forEach(button => button.onclick = () => { const meal = meals.find(item => item.id === button.dataset.order); if (meal && confirm(`Confirm order for ${meal.name} at ₹${meal.price}?`)) { const orders = JSON.parse(localStorage.getItem('homebite_orders') || '[]'); orders.push({ name: meal.name, price: meal.price, orderedAt: new Date().toLocaleString() }); localStorage.setItem('homebite_orders', JSON.stringify(orders)); toast('Order confirmed — enjoy your meal!'); } }); };
  async function landingMeals() { const grid = document.getElementById('meals-grid'); if (!grid) return; try { const meals = (await api('/api/meals')).meals; grid.innerHTML = meals.length ? meals.slice(0, 6).map(meal => card(meal)).join('') : '<p class="text-stone-500">Fresh cook listings will appear here soon.</p>'; bindCards(grid, meals); } catch { grid.innerHTML = '<p class="text-stone-500">Unable to load meals right now.</p>'; } }
  async function customerBrowser() { const main = document.querySelector('main'); if (!main) return; const section = document.createElement('section'); section.className = 'mx-auto max-w-6xl px-4 py-10 md:px-6'; section.innerHTML = `<div class="rounded-3xl border border-stone-100 bg-white p-6 shadow-sm"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="font-serif text-3xl font-bold">Browse fresh listings</h2><p class="mt-1 text-stone-500">Meals published by local HomeBite cooks.</p></div></div><div class="mt-5 flex flex-col gap-3 sm:flex-row"><input id="listing-search" placeholder="Search meals" class="rounded-xl border border-stone-200 px-4 py-3"><select id="listing-cuisine" class="rounded-xl border border-stone-200 px-4 py-3"><option value="">All cuisines</option></select></div><div id="listing-results" class="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><p>Loading meals…</p></div><div class="mt-8 border-t pt-5"><h3 class="font-semibold">Your order history</h3><div id="order-history" class="mt-3 text-sm text-stone-500"></div></div></div>`; main.append(section); const results = section.querySelector('#listing-results'), search = section.querySelector('#listing-search'), cuisine = section.querySelector('#listing-cuisine'); try { const meals = (await api('/api/meals')).meals; [...new Set(meals.map(meal => meal.cuisine))].forEach(value => cuisine.insertAdjacentHTML('beforeend', `<option>${escape(value)}</option>`)); const render = () => { const filtered = meals.filter(meal => (!search.value || meal.name.toLowerCase().includes(search.value.toLowerCase())) && (!cuisine.value || meal.cuisine === cuisine.value)); results.innerHTML = filtered.length ? filtered.map(meal => card(meal, true)).join('') : '<p class="text-stone-500">No meals match your search.</p>'; const orders = JSON.parse(localStorage.getItem('homebite_orders') || '[]'); section.querySelector('#order-history').innerHTML = orders.length ? orders.slice().reverse().map(order => `<p>${escape(order.name)} — ₹${order.price} <span class="text-stone-400">${order.orderedAt}</span></p>`).join('') : 'No orders yet.'; bindCards(results, meals); }; search.oninput = render; cuisine.onchange = render; render(); } catch (error) { results.innerHTML = `<p class="text-red-600">${escape(error.message)}</p>`; } }
  async function initialise() { const user = await getUser(); if (location.pathname.includes('customer_dashboard') && (!user || user.role !== 'customer')) return location.assign('login.html'); if (location.pathname.includes('homecook_dashboard') && (!user || user.role !== 'homecook')) return location.assign('login.html'); document.querySelectorAll('[data-homebite-user]').forEach(node => node.textContent = user ? `Hi, ${user.username}` : ''); document.querySelectorAll('[data-homebite-login]').forEach(node => { if (user) { node.href = user.role === 'homecook' ? 'homecook_dashboard.html' : 'customer_dashboard.html'; node.textContent = `Hi, ${user.username}`; } }); document.querySelectorAll('[data-homebite-logout]').forEach(node => node.onclick = async () => { try { await api('/api/auth/logout', { method: 'POST' }); } finally { location.href = 'index.html'; } }); landingMeals(); if (location.pathname.includes('customer_dashboard')) customerBrowser(); }
  window.HomeBite = { api, toast, getUser, card, escape };
  document.addEventListener('DOMContentLoaded', initialise);
})();
