const express = require('express');
const path = require('path');
const authRoutes = require('./src/routes/auth');
const mealRoutes = require('./src/routes/mealRoutes');
const { requirePageAuth } = require('./src/middleware/auth');
const { notFound, errorHandler } = require('./src/middleware/errorHandler');

const app = express();
const PORT = process.env.PORT || 3000;
app.disable('x-powered-by');
app.use(express.urlencoded({ extended: false }));
app.use(express.json({ limit: '100kb' }));
app.get('/customer_dashboard.html', requirePageAuth('customer'), (_req, res) => res.sendFile(path.join(__dirname, 'customer_dashboard.html')));
app.get('/homecook_dashboard.html', requirePageAuth('homecook'), (_req, res) => res.sendFile(path.join(__dirname, 'homecook_dashboard.html')));
app.use('/api/auth', authRoutes);
app.use('/api/meals', mealRoutes);
app.get('/login', (_req, res) => res.sendFile(path.join(__dirname, 'login.html')));
app.use(express.static(__dirname));
app.use('/api', notFound);
app.use(errorHandler);
if (require.main === module) app.listen(PORT, () => console.log(`HomeBite server running at http://localhost:${PORT}`));
module.exports = app;
