const express = require('express');
const path = require('path');
const authRoutes = require('./src/routes/auth');
const mealRoutes = require('./src/routes/mealRoutes');
const { requirePageAuth } = require('./src/middleware/auth');
const { notFound, errorHandler } = require('./src/middleware/errorHandler');

const app = express();
const PORT = process.env.PORT || 3000;
const clientBuild = path.join(__dirname, 'dist');
app.disable('x-powered-by');
app.use(express.urlencoded({ extended: false }));
app.use(express.json({ limit: '4mb' }));
app.use('/api/auth', authRoutes);
app.use('/api/meals', mealRoutes);
app.get(['/login.html', '/login'], (_req, res) => res.sendFile(path.join(clientBuild, 'index.html')));
app.get(['/register.html', '/register'], (_req, res) => res.sendFile(path.join(clientBuild, 'index.html')));
app.get(['/customer_dashboard.html', '/customer-dashboard'], requirePageAuth('customer'), (_req, res) => res.sendFile(path.join(clientBuild, 'index.html')));
app.get(['/homecook_dashboard.html', '/cook-dashboard'], requirePageAuth('homecook'), (_req, res) => res.sendFile(path.join(clientBuild, 'index.html')));
app.use(express.static(clientBuild));
app.use('/api', notFound);
app.get(/.*/, (_req, res) => res.sendFile(path.join(clientBuild, 'index.html')));
app.use(errorHandler);
if (require.main === module) app.listen(PORT, () => console.log(`HomeBite server running at http://localhost:${PORT}`));
module.exports = app;
